### ISSUE TITLE
REF-Atas 

### ISSUE THREAD

**Issue by FilhoDoan** [Requisitos-de-Software/2023.2-BRBMobilidade#32]
# Descrição
Fazer refatoração dos documentos da primeira entrega :
- **Atas**
## Observações
- Trazer link do youtube(Não Listado) 

## Prazos
- Entrega: 25/09
- Revisão: 26/09

**Comment by JoelSRangel** [comment]
Foram feitas as confecções das Atas pelo Doan, e no dia 26/09 realizei a revisão das atas das reuniões 1, 2 , 3 e 4.
