### ISSUE TITLE
REF-Avaliação dos Sites Escolhidos

### ISSUE THREAD

**Issue by FilhoDoan** [Requisitos-de-Software/2023.2-BRBMobilidade#34]
# Descrição
Fazer refatoração dos documentos da primeira entrega :
- **Avaliação Sites Escolhidos**
## Observações
- Fazer avaliação dos sites que optamos 

## Prazos
- Entrega: 25/09
- Revisão: 26/09

**Comment by JoelSRangel** [comment]
Foi feita a revisão do docs de aplicativo selecionado. Nele, não há a avaliação detalhada de cada site considerado, e há a dúvida sobre a adição disso no documento.
